# 2장 넘파이(NumPy)로 공부하는 선형대수
- 2.1 데이터와 행렬
- 2.2 벡터와 행렬의 연산
- 2.3 행렬의 성질
- 2.4 선형 연립방정식과 역행렬

***
# 정의

    - 영어로된 내용의 정의와 맞는 정의의 내용을 찾으시오
##### 정의
1. transpose operation : 
2. diagonal matrix : 
3. identity matrix : 
4. symmetric matrix : 
5. linear combination : 
6. inner product : 
7. weighted sum : 
8. cosine similarity : 
10. trace : 
11. determinant : 
12. inverse matrix : 

##### 내용
1. 역함수를 구할때 이용되며 $det(A) = \sum_{i=1}^N\{(-1)^{i+j_0}M_{i,j_0}a_{i,j_0}$으로 정의된다
2. 복수의 데이터를 단순히 합하는 것이 아니라 각각의 수에 어떤 가중치 값을 곱한 후 이 곱셈 결과들을 다시 합한 것을 말한다.
3. 행렬의 행과 열을 바꾸는 연산 
4. 벡터/행렬에 스칼라값을 곱한 후 더하거나 뺀 것
5. 벡터의 내적을 이용하여 두 벡터가 닮은 정도를 정량적으로 파악하는 방법
6. 정방행령에서만 정의되며 모든 대각요소의 합을 의미한다
7. 원래의 행렬에서 내적연산을 했을 시 항등행렬이 나오는 함수를 말한다
8. 대각행렬 중에서 모든 대각성분의 값이 1인 행렬
9. 행렬에서 모든 비대각 요소가 0인 행렬
10. 두 벡터를 곱하는 방법중 하나, 조건으로 두 벡터의 차원이 같아야 하며 앞의 벡터가 행 벡터, 뒤의 벡터가 열 벡터여야 한다
11. 전치연산을 통해 얻은 전치행렬과 원래의 행렬이 같은 행렬

##### 영어문제 이유
- 한국인이 쓴 논문과 여러 공부자료에서 한글 해석이 아닌 영어표현으로 설명한 자료도 있어 기본 정의여도 영어로 된 표현도 알면 좋을꺼 같아서 문제로 만들었습니다.
- 또한 기본 정의 + 내용 문제 내용도 넣어 1 + 1 문제로 만들었습니다

***
# 증명
    - 증명을 파이썬으로 만들어도 되고 종이에 풀고 사진으로 올려 주세요

1. 행렬 놈(norm)의 정의를 쓰시오
$$ ||A||_2 = $$

2. 다음 식을 증명하시오(단 X는 N x M행렬일때)
$$ tr(X(X^TX)^{-1}X^T) = M \;\;\;$$ 

3. 다음 식이 성립함을 증명하시오.
$$ x^TAx = \frac{1}{2}x^T(A + A^T)x$$

4. 다음 식이 성립함을 증명하시오
$$ A((A^{-1}A)^{-1})^{-1}(B^TB^{-1})^{-1}(C^T)^{-1}(AB^TC^T)^{-1}A^{-1} C = ABC $$

***
# 문제풀이

1. 다음이 참인지 거짓인지 쓰시오
    - 대칭행렬은 영행렬이 아닌 행렬이 모든 비대각 요소가 0인 정방행렬를 말한다 $[\;\;]$
    - 행렬과 그행렬의 전치행렬은 다음을 만족한다 $[\;\;]$
    $$ det(A) = det(A^T) $$
    - 행렬의 행렬식은 항상 다음을 만족한다 $[\;\;]$
    $$ det(AB) > set(A)det(B) $$
    - 행렬의 놈은 다음을 만족한다$[\;\;]$
    $$||A + B|| >= ||A|| + ||B||$$
    $$||AB|| >= ||A||||B||$$

2. 다음 식을 푸시오
    - 벡터 * 스칼라
    $$ \frac{1}{2}\begin{bmatrix}10 \\ -4 \\ 6 \end{bmatrix} = $$
    - 벡터 * 벡터
    $$ \begin{bmatrix}2 & 2 & 5 & 4 \end{bmatrix}\begin{bmatrix}1 \\ -1 \\ 1 \\ -1 \end{bmatrix} = $$
    - 행렬의 내적
    $$\begin{bmatrix}1 & -1 \\ -1 & 1 \end{bmatrix}
\begin{bmatrix}2 & 2 \\ 3 & 3 \end{bmatrix} = $$
    - 해당 식이 양의 정부호 인지 양의 준정부호 인지 둘다 아닌지 쓰시오
    - 1번 $$:  \begin{bmatrix}1 & -1 \\ -1 & 1 \end{bmatrix} $$
    - 2번 $$:  \begin{bmatrix}3 & -1 & 0 \\ -1 & 2 & -1 \\ 0 & -1 & 3 \end{bmatrix} $$

***
# 코딩문제

In [ ]:
import numpy as np
x1 = np.array([[1, 2],[3, 4]])
x2 = np.array([[1, 0],[0, 1]])
x3 = np.array([[1],[2]])

### 1. x1과 x2를 더하시오

In [5]:
## 1. 더하기


array([[2, 2],
       [3, 5]])

### 2. x1과 x2를 곱하시오

In [8]:
## 2. 곱하기


array([[1, 2],
       [3, 4]])

### 3. x3의 전치행렬을 구하시오

In [11]:
## 3. 전치행렬


array([[1, 2]])

### 4. 크기가 2인 영행렬, 일행렬, 항등행렬을 만드시오

In [19]:
## 4. 영행렬, 일행렬, 항등행렬


[[0. 0.]
 [0. 0.]]

[[1. 1.]
 [1. 1.]]

[[1. 0.]
 [0. 1.]]


### 5. x1의 행렬식을 구하시오

In [22]:
## norm


5.477225575051661

### 6. x2 의 대각합을 구하여라

In [23]:
## 대각합


2

### 7.  x1의 행렬식을 구하시오

In [24]:
## 행렬식


-2.0000000000000004

### 8. x1의 역행렬을 구하시오

In [26]:
## 역행렬
np.linalg.inv(x1)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

### 9. 최소자승문제를 해결하라

In [32]:
A = np.array([[1,1,0],[0,1,1],[1,1,1],[1,1,2]])
B = np.array([[2],[2],[3],[4.1]])

 힌트 x = $(A^TA)^{-1}AB$

In [33]:
## 

array([[1.03333333],
       [0.95      ],
       [1.05      ]])